export const ITEM_DELETE = "ITEM_DELETE"
export const ITEM_ADD = "ITEM_ADD"
export const ITEM_RENAME = "ITEM_RENAME"

export const CONTAINER_DELETE = "CONTAINER_DELETE"
export const CONTAINER_ADD = "CONTAINER_ADD"
export const CONTAINER_RENAME = "CONTAINER_RENAME"

export const SET_ACCOUNT = "SET_ACCOUNT"

export const SET_ARRANGEMENTS = "SET_ARRANGEMENTS"

export const SET_REAL_DATA = "SET_REAL_DATA"

export const SET_UNASSIGNED = "SET_UNASSIGNED"
export const SET_SNAPSHOT = "SET_SNAPSHOT"

export const SAVE_STATE = "SAVE_STATE"

export const SET_TSV_EXPORT = "SET_TSV_EXPORT"

export const ARRANGEMENT_RENAME = "ARRANGEMENT_RENAME"