export const ITEM_DELETE = "ITEM_DELETE"
export const ITEM_ADD = "ITEM_ADD"
export const ITEM_UPDATE = "ITEM_UPDATE"

export const CONTAINER_DELETE = "CONTAINER_DELETE"
export const CONTAINER_ADD = "CONTAINER_ADD"
export const CONTAINER_EDIT = "CONTAINER_EDIT"

export const SNAPSHOT_ADD = "SNAPSHOT_ADD"
export const SNAPSHOT_DELETE = "SNAPSHOT_DELETE"
export const SNAPSHOT_RENAME = "SNAPSHOT_RENAME"
export const SNAPSHOT_REPOSITION = "SNAPSHOT_REPOSITION"
export const SNAPSHOT_SET_CONTAINERS = "SNAPSHOT_SET_CONTAINERS"

export const SET_ACCOUNT = "SET_ACCOUNT"
export const LOGOUT = "LOGOUT"

export const SET_USERS = "SET_USERS"

export const SET_ARRANGEMENTS = "SET_ARRANGEMENTS"

export const SET_REAL_DATA = "SET_REAL_DATA"

export const SET_UNASSIGNED_ITEMS = "SET_UNASSIGNED_ITEMS"
export const SET_CONTAINER_ITEMS = "SET_SNAPSHOT"

export const SAVE_STATE = "SAVE_STATE"

export const SET_TSV_EXPORT = "SET_TSV_EXPORT"

export const ARRANGEMENT_RENAME = "ARRANGEMENT_RENAME"

export const SET_DISPLAY_NOTES = "SET_DISPLAY_NOTES"